
version: "3.8"

services:
  backend:
    build:
      context: ./back-query-builder 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back-query-builder:/app
    env_file:
      - ./back-query-builder/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - query_network

  frontend:
    build:
      context: ./front-query-builder
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-query-builder:/app
      - /app/node_modules
    env_file:
      - ./front-query-builder/.env
    depends_on:
      - backend
    networks:
      - query_network

networks:
  query_network:
    driver: bridge
